spring:
  application:
    name: gdtech-hackathon

  # Jackson配置
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null

server:
  port: 8080
  servlet:
    context-path: /api

# 飞书配置
feishu:
  app-id: ${FEISHU_APP_ID:cli_a862c494a9431013}
  app-secret: ${FEISHU_APP_SECRET:tUw7iGj2MKCDVXyGsqJWdh7iLuhqhPc4}

  # 多维表格配置
  base:
    app-token: ${FEISHU_BASE_APP_TOKEN:VZ77bJ9MvalDxqscf0Bcfh0Tnjp}
    tables:
      projects: ${FEISHU_TABLE_PROJECTS:tblGAbkdJKqTOlEw}
      investors: ${FEISHU_TABLE_INVESTORS:tblDp18p0G4xcADk}
      investments: ${FEISHU_TABLE_INVESTMENTS:tblh9DMhfC4dQHMJ}
      config: ${FEISHU_TABLE_CONFIG:tbl43OV7SBtzFzw1}

# 百度统计配置（支持多账号）
# 注意：百度统计API需要通过OAuth2.0完整授权流程获取access_token
# client_credentials方式获取的token无法访问统计数据API
baidu:
  tongji:
    # UV同步间隔（分钟）
    sync-interval: 10
    # 多个百度统计账号配置
    # 推荐：直接配置已授权的access_token和refresh_token
    accounts:
      account1:
        client-id: ${BAIDU_ACCOUNT1_CLIENT_ID:pSPZrp0fs3x02wvG0V8WnFByH0j3TekZ}
        client-secret: ${BAIDU_ACCOUNT1_CLIENT_SECRET:HiQPA3MFKp6ayVq60SnYu4QOaDfEaLix}
        # 使用已授权的token（来自zeabur示例项目）
        access-token: ${BAIDU_ACCOUNT1_ACCESS_TOKEN:121.a5389f189bd678178900fbaf180eddc9.YsUSJDM6bXRVRpah7mxH14GpE53P8bV10uNrkbA.EPrJJA}
        refresh-token: ${BAIDU_ACCOUNT1_REFRESH_TOKEN:122.051c0599eb04fa5b60687e85ac0b387d.YsW9Rr6K0_cKFrQE72ViyfWlObEDWKHkwP2Sryn.uw_Jag}
      account2:
        client-id: ${BAIDU_ACCOUNT2_CLIENT_ID:9WdFRWt8Db2aGZVPcCVXBgIYmOQUXTEH}
        client-secret: ${BAIDU_ACCOUNT2_CLIENT_SECRET:tRiVxGdREeQbowK8VUKwA7KLrkZVmP3V}

# 业务配置
hackathon:
  # 晋级名额
  qualified-count: 15

  # 比赛阶段时间配置（用于自动切换阶段，如果不配置则从飞书表格读取）
  stages:
    selection:
      start: 2025-10-24 24:00:00
      end: 2025-11-07 12:00:00
    lock:
      start: 2025-11-07 12:00:00
      end: 2025-11-14 00:00:00
    investment:
      start: 2025-11-14 00:00:00
      end: 2025-11-14 18:00:00

# 日志配置
logging:
  level:
    com.gdtech.hackathon: DEBUG
    com.larksuite.oapi: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
